# Copyright (c) Microsoft Corporation. All rights reserved.


[package]
name = "mcr_ddi_mbor"
version = "0.1.0"
edition = "2021"


[lib]
doctest = false


[dependencies]
arbitrary = { workspace = true, optional = true }


[dev-dependencies]
rand.workspace = true


[features]
array = []
pre_encode = []
post_decode = []
fuzzing = ["arbitrary"]
