# Copyright (C) Microsoft Corporation. All rights reserved.

# use_small_heuristics = "Max"
format_macro_bodies = true
format_macro_matchers = true
group_imports = "StdExternalCrate"
imports_granularity = "Item"
