# Copyright (C) Microsoft Corporation. All rights reserved.
[package]
edition = "2024"
name = "azihsm_fw_app_hsm"
version = "0.0.0"

[dependencies]
azihsm_fw_pal_mgmt.workspace = true
embassy-executor.workspace = true
embassy-sync.workspace = true
embassy-time.workspace = true
futures.workspace = true
tracing.workspace = true

[features]
default = []
std = [
    "embassy-executor/arch-std",
    "embassy-executor/executor-thread",
    "embassy-executor/log",
    "embassy-sync/log",
    "embassy-sync/std",
    "embassy-time/log",
    "embassy-time/std",
]

[lints]
workspace = true
