# Copyright (C) Microsoft Corporation. All rights reserved.
[package]
edition = "2024"
name = "azihsm_fw_mgmt_pal_traits"
version = "0.0.0"

[dependencies]
bitfield-struct.workspace = true
open-enum.workspace = true

[lints]
workspace = true
