# Copyright (C) Microsoft Corporation. All rights reserved.

[package]
name = "masked_key"
version = "0.1.0"
edition = "2021"

[dependencies]
cfg-if.workspace = true
mcr_ddi_mbor.workspace = true
mcr_ddi_types.workspace = true
zerocopy.workspace = true
crypto_env.workspace = true

[dev-dependencies]
crypto.workspace = true

[features]
default = []
use-openssl = ["crypto_env/use-openssl"]
use-symcrypt = ["crypto_env/use-symcrypt"]