# Copyright (C) Microsoft Corporation. All rights reserved.

[package]
name = "test_with_tracing_macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2.workspace = true
quote.workspace = true
syn = { workspace = true, features = [ "full" ] }

[lints]
workspace = true
