# Copyright (C) Microsoft Corporation. All rights reserved.

[package]
name = "crypto_env"
version = "0.1.0"
edition = "2021"

[dependencies]
cfg-if.workspace = true
mcr_ddi_types.workspace = true
crypto.workspace = true

[features]
default = []
use-openssl = ["crypto/use-openssl"]
use-symcrypt = ["crypto/use-symcrypt"]