# Copyright (C) Microsoft Corporation. All rights reserved.
[package]
edition = "2024"
name = "azihsm_fw_plat_std_mgmt"
version = "0.0.0"

[dependencies]
azihsm_fw_pal_mgmt.workspace = true
bitvec.workspace = true
embassy-executor = { features = [
  "arch-std",
  "executor-thread",
  "log",
], workspace = true }
embassy-sync = { features = ["log", "std"], workspace = true }
embassy-time = { features = ["log", "std"], workspace = true }
# futures.workspace = true
parking_lot.workspace = true
tracing.workspace = true

[lints]
workspace = true
