# Copyright (C) Microsoft Corporation. All rights reserved.

[package]
name = "rsa_padding"
version = "0.1.0"
edition = "2021"

[dependencies]
hex.workspace = true
thiserror.workspace = true
tracing.workspace = true

[target.'cfg(target_os = "linux")'.dev-dependencies]
openssl.workspace = true

[lints]
workspace = true
