# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
edition = "2021"
name = "azihsm_ddi_nix"
version = "0.1.0"

[lib]
doctest = false

[dependencies]
azihsm_ddi_interface.workspace = true
azihsm_ddi_mbor.workspace = true
azihsm_ddi_types.workspace = true
bitfield-struct.workspace = true
glob.workspace = true
nix.workspace = true
parking_lot.workspace = true
tracing.workspace = true

[lints]
workspace = true
