# Copyright (c) Microsoft Corporation. All rights reserved.

[package]
name = "mcr_ddi_derive"
version = "0.1.0"
edition = "2021"
autotests = false

[lib]
proc-macro = true
doctest = false

[dependencies]
darling.workspace = true
paste.workspace = true
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true

[dev-dependencies]
trybuild.workspace = true
mcr_ddi_mbor.workspace = true
rand.workspace = true
open-enum.workspace = true

[[test]]
name = "compile_tests"
path = "tests/compile_tests.rs"
