# Copyright (C) Microsoft Corporation. All rights reserved.

[package]
edition = "2024"
name = "azihsm_fw_plat_std_hsm"
version = "0.0.0"

[dependencies]
embassy-executor = { features = [
  "arch-std",
  "executor-thread",
  "log",
], workspace = true }
embassy-sync = { features = ["log", "std"], workspace = true }
embassy-time = { features = ["log", "std"], workspace = true }
# futures.workspace = true
tracing.workspace = true

[lints]
workspace = true
