# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
edition = "2024"
name = "azihsm_fw_plat_std"
version = "0.0.0"

[dependencies]
azihsm_fw_mgmt_app = { features = ["pal-std"], workspace = true }
embassy-executor = { features = [
  "arch-std",
  "executor-thread",
  "log",
], workspace = true }
embassy-sync = { features = ["log", "std"], workspace = true }
embassy-time = { features = ["log", "std"], workspace = true }
parking_lot.workspace = true
static_cell.workspace = true
strum.workspace = true
strum_macros.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[lints]
workspace = true
